trigger: none

parameters:
  - name: mode
    displayName: 'Apply or Destroy'
    type: string
    values:
    - Apply
    - Destroy

pool:
  vmImage: ubuntu-latest
steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.8'

- task: TerraformTaskV2@2
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Terraform_Play'
    backendAzureRmResourceGroupName: 'TF_State'
    backendAzureRmStorageAccountName: 'gaterraform'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'GA-TF-Statefile'

- ${{ if eq(parameters.mode, 'Apply') }}:
    - task: TerraformTaskV2@2
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Terraform_Play'

- ${{ if eq(parameters.mode, 'Apply') }}:
    - task: TerraformTaskV2@2
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'Terraform_Play'

- ${{ if eq(parameters.mode, 'Destroy') }}:
  - task: TerraformTaskV2@2
    displayName: 'Terraform Destroy'
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      environmentServiceNameAzureRM: 'Terraform_Play'
